#!/bin/bash

set -e

cd $(dirname $0)

DOCKER_TARGET=${DOCKER_TARGET:-diamino}
IMAGE_NAME=xilinx-ise
IMAGE_TAG=14.7

# start small webserver to hold install files
cd xilinx-installer
python3 -m http.server 8765 --bind 0.0.0.0 >/dev/null 2>&1 &
HTTP_SERVER_PID=$!
trap "echo 'stopping $HTTP_SERVER_PID' ; if [ $HTTP_SERVER_PID ] ; then kill $HTTP_SERVER_PID ; fi" SIGINT SIGTERM EXIT
cd ..

xhost + 127.0.0.1

docker build --rm -t ${DOCKER_TARGET}/${IMAGE_NAME}:${IMAGE_TAG} .
docker tag ${DOCKER_TARGET}/${IMAGE_NAME}:${IMAGE_TAG} ${DOCKER_TARGET}/${IMAGE_NAME}:latest
