#!/bin/bash

DOCKER_IMAGE=diamino/xilinx-ise

XILINX_LIC=${XILINX_LIC:-$HOME/.Xilinx/Xilinx.lic}
XILINX_WORK=${XILINX_WORK:-${PWD}}

docker run -it -e DISPLAY=host.docker.internal:0 \
           -v ${XILINX_LIC}:/root/.Xilinx/Xilinx.lic \
           -v ${XILINX_WORK}:/build \
           --rm ${DOCKER_IMAGE} /usr/local/bin/wrapper "$@"
